/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_pateo_audiovendorinterface_IAudioVendor */

#ifndef _Included_com_pateo_audiovendorinterface_IAudioVendor
#define _Included_com_pateo_audiovendorinterface_IAudioVendor
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_pateo_audiovendorinterface_IAudioVendor
 * Method:    test
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_pateo_audiovendorinterface_IAudioVendor_test
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
